[workspace]
resolver = "2"
members = [
    "crates/qefro-core",
    "crates/qefro-db",
    "crates/qefro-api",
    "crates/qefro-auth",
    "crates/qefro-permissions",
    "crates/qefro-workflow",
    "crates/qefro-tenant",
    "crates/qefro-events",
    "crates/qefro-search",
    "crates/qefro-agent",
    "crates/qefro-cli",
    "examples/basic-crm",
    "examples/restaurant",
]

[workspace.package]
version = "0.7.0"
edition = "2021"
license = "MIT"
authors = ["Qefro"]
description = "Rust-native, metadata-driven framework for multi-tenant business applications"
repository = "https://github.com/qefro-ai/qefro-framework"
homepage = "https://github.com/qefro-ai/qefro-framework"

[workspace.dependencies]
qefro-core = { version = "0.7.0", path = "crates/qefro-core" }
qefro-db = { version = "0.7.0", path = "crates/qefro-db" }
qefro-api = { version = "0.7.0", path = "crates/qefro-api" }
qefro-auth = { version = "0.7.0", path = "crates/qefro-auth" }
qefro-permissions = { version = "0.7.0", path = "crates/qefro-permissions" }
qefro-workflow = { version = "0.7.0", path = "crates/qefro-workflow" }
qefro-tenant = { version = "0.7.0", path = "crates/qefro-tenant" }
qefro-events = { version = "0.7.0", path = "crates/qefro-events" }
qefro-search = { version = "0.7.0", path = "crates/qefro-search" }
qefro-agent = { version = "0.7.0", path = "crates/qefro-agent" }
qefro-restaurant = { version = "0.7.0", path = "examples/restaurant" }
qefro-crm = { version = "0.7.0", path = "examples/basic-crm" }
toml = "0.8"
semver = "1"
zip = { version = "0.6", default-features = false, features = ["deflate"] }

tokio = { version = "1", features = ["full"] }
axum = { version = "0.8", features = ["macros", "json", "multipart"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "uuid", "chrono", "json", "migrate"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
thiserror = "2"
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
async-trait = "0.1"
jsonwebtoken = "9"
argon2 = "0.5"
password-hash = "0.5"
rand = "0.8"
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace", "fs"] }
regex = "1"
futures = "0.3"
http = "1"
hex = "0.4"
sha2 = "0.10"

[profile.dev]
debug = 1
